spring:
  application:
    name: search-web
server:
  port: 7767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eager-load:
    clients: search-service
    enabled: true
