spring:
  redis:
    host: 139.129.97.123
    port: 6379
    password: p@ssw0rd
    jedis:
      pool:
        max-active: 20
  application:
    name: cache-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765