spring:
  application:
    name: login-web

server:
  port: 7768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eager-load:
    clients: cache-service,login-service
    enabled: true