spring:
  application:
    name: index-web

server:
  port: 7763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eager-load:
    clients: cart-web,login-service,index-service
    enabled: true