spring:
  data:
    solr:
      host: http://139.129.97.123:28983/solr/ik_core
  datasource:
    url: jdbc:mysql://139.129.97.123:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  application:
    name: search-service
server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  # 3.1 扫描映射文件.
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #3.2 配置驼峰映射.
    map-underscore-to-camel-case: true
  # 3.3 配置别名.
  type-aliases-package: com.qf.entity