spring:
  application:
    name: register-web

server:
  port: 7762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eager-load:
    clients: email-service,login-service,cache-service
    enabled: true